# **Series**

In [ ]:
import pandas as pd

In [ ]:
x=[3,4,5,6,7,8]
var = pd.Series(x)
print(var)
print(type(var))
print(var[2])

0    3
1    4
2    5
3    6
4    7
5    8
dtype: int64
<class 'pandas.core.series.Series'>
5

In [7]:
x=[3,4,5,6,7,8]
var = pd.Series(x,index=['a','b','c','d','e','f'])
print(var)
print(type(var))
print(var[2])

a    3
b    4
c    5
d    6
e    7
f    8
dtype: int64
<class 'pandas.core.series.Series'>
5

<ipython-input-7-94ed151e0f78>:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var[2])

In [8]:
x=[3,4,5,6,7,8]
var = pd.Series(x,index=['a','b','c','d','e','f'],dtype='float')
print(var)
print(type(var))
print(var[2])

a    3.0
b    4.0
c    5.0
d    6.0
e    7.0
f    8.0
dtype: float64
<class 'pandas.core.series.Series'>
5.0

<ipython-input-8-ab5d45f6b669>:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var[2])

In [9]:
x=[3,4,5,6,7,8]
var = pd.Series(x,index=['a','b','c','d','e','f'],dtype='float',name='Python')
print(var)
print(type(var))
print(var[2])

a    3.0
b    4.0
c    5.0
d    6.0
e    7.0
f    8.0
Name: Python, dtype: float64
<class 'pandas.core.series.Series'>
5.0

<ipython-input-9-743ee36579a9>:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(var[2])

In [10]:
dic={'name':['Python','C++','C','Java'],'popularity':[12,13,14,15],'Rank':[1,4,3,2]}
var= pd.Series(dic)
print(var)

name          [Python, C++, C, Java]
popularity          [12, 13, 14, 15]
Rank                    [1, 4, 3, 2]
dtype: object

In [17]:
s=pd.Series(12)
print(s)
print(type(s))

0    12
dtype: int64
<class 'pandas.core.series.Series'>

In [18]:
s=pd.Series(12,index=[1,2,3,4,5,6])
print(s)
print(type(s))

1    12
2    12
3    12
4    12
5    12
6    12
dtype: int64
<class 'pandas.core.series.Series'>

In [19]:
s1=pd.Series(12,index=[1,2,3,4,5,6])
s2=pd.Series(12,index=[1,2,3,4])
print(s1+s2)

1    24.0
2    24.0
3    24.0
4    24.0
5     NaN
6     NaN
dtype: float64

# **DataFrame**

In [22]:
l=[1,2,3,4,5,6]
var=pd.DataFrame(l)
print(var)
print(type(var))

   0
0  1
1  2
2  3
3  4
4  5
5  6
<class 'pandas.core.frame.DataFrame'>

In [23]:
dic={'a':[1,2,3,4,5],'s':[1,2,3,4,5]}
var=pd.DataFrame(dic)
print(var)
print(type(var))

   a  s
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
<class 'pandas.core.frame.DataFrame'>

In [24]:
dic={'a':[1,2,3,4,5],'s':[1,2,3,4,5]}
var=pd.DataFrame(dic,columns=['a'])
print(var)
print(type(var))

   a
0  1
1  2
2  3
3  4
4  5
<class 'pandas.core.frame.DataFrame'>

In [25]:
dic={'a':[1,2,3,4,5],'s':[1,2,3,4,5],'d':[1,2,3,4,5],1:[1,2,3,4,5]}
var=pd.DataFrame(dic,columns=['a',1])
print(var)
print(type(var))

   a  1
0  1  1
1  2  2
2  3  3
3  4  4
4  5  5
<class 'pandas.core.frame.DataFrame'>

In [26]:
dic={'a':[1,2,3,4,5],'s':[1,2,3,4,5],'d':[1,2,3,4,5],1:[1,2,3,4,5]}
var=pd.DataFrame(dic,columns=['a',1],index=['a','s','d','g','f'])
print(var)
print(type(var))

   a  1
a  1  1
s  2  2
d  3  3
g  4  4
f  5  5
<class 'pandas.core.frame.DataFrame'>

In [29]:
dic={'a':[1,2,3,4,5],'s':[1,2,3,4,5],'d':[1,2,3,4,5],1:[1,2,3,4,5]}
var=pd.DataFrame(dic)
print(var)
print(var['a'][3])
print(type(var))

   a  s  d  1
0  1  1  1  1
1  2  2  2  2
2  3  3  3  3
3  4  4  4  4
4  5  5  5  5
4
<class 'pandas.core.frame.DataFrame'>

In [31]:
list=[[1,2,3,4,5],[11,12,13,14,15]]
var =pd.DataFrame(list)
print(var)
print(type(var))

    0   1   2   3   4
0   1   2   3   4   5
1  11  12  13  14  15
<class 'pandas.core.frame.DataFrame'>

In [32]:
sr={'s':pd.Series([1,2,3,4]),'r':pd.Series([1,2,3,4])}
var=pd.DataFrame(sr)
print(var)
print(type(var))

   s  r
0  1  1
1  2  2
2  3  3
3  4  4
<class 'pandas.core.frame.DataFrame'>

# Arithmetic **operations**

In [33]:
var=pd.DataFrame({'A':[1,2,3,4],'B':[5,6,7,8]})
print(var)

   A  B
0  1  5
1  2  6
2  3  7
3  4  8

In [34]:
var['C']=var['A']+var['B']
var

   A  B   C
0  1  5   6
1  2  6   8
2  3  7  10
3  4  8  12

In [35]:
var['C']=var['A']-var['B']
var

   A  B  C
0  1  5 -4
1  2  6 -4
2  3  7 -4
3  4  8 -4

In [36]:
var['C']=var['A']*var['B']
var

   A  B   C
0  1  5   5
1  2  6  12
2  3  7  21
3  4  8  32

In [37]:
var['C']=var['A']/var['B']
var

   A  B         C
0  1  5  0.200000
1  2  6  0.333333
2  3  7  0.428571
3  4  8  0.500000

In [44]:
var=pd.DataFrame({'A':[10,20,30,40],'B':[15,16,17,18]})
print(var)

    A   B
0  10  15
1  20  16
2  30  17
3  40  18

In [43]:
var['(<=20)']=var['A']<=20
print(var)

    A   B  (<=20)
0  10  15    True
1  20  16    True
2  30  17   False
3  40  18   False

# **Insert**

In [46]:
var=pd.DataFrame({'A':[1,2,3,4,5],'C':[9,8,7,6,5]})
print(var)

   A  C
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5

In [47]:
var.insert(1,'B',var['A'])
print(var)

   A  B  C
0  1  1  9
1  2  2  8
2  3  3  7
3  4  4  6
4  5  5  5

In [48]:
var.insert(3,'D',[11,12,13,14,15])
print(var)

   A  B  C   D
0  1  1  9  11
1  2  2  8  12
2  3  3  7  13
3  4  4  6  14
4  5  5  5  15

In [50]:
var['D']=var['A'][:3]
print(var)

   A  B  C    D
0  1  1  9  1.0
1  2  2  8  2.0
2  3  3  7  3.0
3  4  4  6  NaN
4  5  5  5  NaN

# **Delete**

In [60]:
var=pd.DataFrame({'A':[1,2,3,4,5],'B':[9,8,7,6,5],'C':[9,8,7,6,5]})
print(var)

   A  B  C
0  1  9  9
1  2  8  8
2  3  7  7
3  4  6  6
4  5  5  5

In [61]:
d=var.pop('C')
d

0    9
1    8
2    7
3    6
4    5
Name: C, dtype: int64

In [62]:
print(var)

   A  B
0  1  9
1  2  8
2  3  7
3  4  6
4  5  5

In [63]:
del var['B']
var

   A
0  1
1  2
2  3
3  4
4  5

# Write **CSV**

In [65]:
var=pd.DataFrame({'A':[1,2,3,4,5,6],'B':[1,2,3,4,5,6],'C':[1,2,3,4,5,6]})
var

   A  B  C
0  1  1  1
1  2  2  2
2  3  3  3
3  4  4  4
4  5  5  5
5  6  6  6

In [66]:
var.to_csv("Test_new.csv")

In [67]:
var.to_csv("Test_new1.csv",index=False)

In [68]:
var.to_csv("Test_new2.csv",header=[1,2,3])

# Read **CSV**

In [72]:
csv=pd.read_csv('/content/Titanic.csv')
csv

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [76]:
csv1=pd.read_csv('/content/Titanic.csv',nrows=2)
csv1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C

In [77]:
csv2=pd.read_csv('/content/Titanic.csv',usecols=['Name'])
csv2

                                                 Name
0                             Braund, Mr. Owen Harris
1   Cumings, Mrs. John Bradley (Florence Briggs Th...
2                              Heikkinen, Miss. Laina
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                            Allen, Mr. William Henry
5                                    Moran, Mr. James
6                             McCarthy, Mr. Timothy J
7                      Palsson, Master. Gosta Leonard
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                 Nasser, Mrs. Nicholas (Adele Achem)
10                    Sandstrom, Miss. Marguerite Rut
11                           Bonnell, Miss. Elizabeth
12                     Saundercock, Mr. William Henry
13                        Andersson, Mr. Anders Johan
14               Vestrom, Miss. Hulda Amanda Adolfina
15                   Hewlett, Mrs. (Mary D Kingcome)
16                               Rice, Master. Eugene
17                       Williams, Mr. Charles Eugene
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...
19                            Masselmani, Mrs. Fatima
20                               Fynney, Mr. Joseph J
21                              Beesley, Mr. Lawrence
22                        McGowan, Miss. Anna "Annie"
23                       Sloper, Mr. William Thompson

In [78]:
csv3=pd.read_csv('/content/Titanic.csv',usecols=['Name','Sex'])
csv3

                                                 Name     Sex
0                             Braund, Mr. Owen Harris    male
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                              Heikkinen, Miss. Laina  female
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                            Allen, Mr. William Henry    male
5                                    Moran, Mr. James    male
6                             McCarthy, Mr. Timothy J    male
7                      Palsson, Master. Gosta Leonard    male
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9                 Nasser, Mrs. Nicholas (Adele Achem)  female
10                    Sandstrom, Miss. Marguerite Rut  female
11                           Bonnell, Miss. Elizabeth  female
12                     Saundercock, Mr. William Henry    male
13                        Andersson, Mr. Anders Johan    male
14               Vestrom, Miss. Hulda Amanda Adolfina  female
15                   Hewlett, Mrs. (Mary D Kingcome)   female
16                               Rice, Master. Eugene    male
17                       Williams, Mr. Charles Eugene    male
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19                            Masselmani, Mrs. Fatima  female
20                               Fynney, Mr. Joseph J    male
21                              Beesley, Mr. Lawrence    male
22                        McGowan, Miss. Anna "Annie"  female
23                       Sloper, Mr. William Thompson    male

In [79]:
csv4=pd.read_csv('/content/Titanic.csv',usecols=[4])
csv4

       Sex
0     male
1   female
2   female
3   female
4     male
5     male
6     male
7     male
8   female
9   female
10  female
11  female
12    male
13    male
14  female
15  female
16    male
17    male
18  female
19  female
20    male
21    male
22  female
23    male

In [81]:
csv5=pd.read_csv('/content/Titanic.csv',skiprows=[3])
csv5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
3,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
4,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
5,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
6,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
7,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
8,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
9,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
10,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
11,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
12,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
13,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
14,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
15,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
16,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
17,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
18,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
19,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
20,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
21,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
22,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [82]:
csv6=pd.read_csv('/content/Titanic.csv',index_col='Name')
csv6

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Name,,,,,,,,,,,
"Braund, Mr. Owen Harris",1,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",2,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
"Heikkinen, Miss. Laina",3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
"Futrelle, Mrs. Jacques Heath (Lily May Peel)",4,1,1,female,35.0,1,0,113803,53.1000,C123,S
"Allen, Mr. William Henry",5,0,3,male,35.0,0,0,373450,8.0500,NaN,S
"Moran, Mr. James",6,0,3,male,NaN,0,0,330877,8.4583,NaN,Q
"McCarthy, Mr. Timothy J",7,0,1,male,54.0,0,0,17463,51.8625,E46,S
"Palsson, Master. Gosta Leonard",8,0,3,male,2.0,3,1,349909,21.0750,NaN,S
"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",9,1,3,female,27.0,0,2,347742,11.1333,NaN,S
"Nasser, Mrs. Nicholas (Adele Achem)",10,1,2,female,14.0,1,0,237736,30.0708,NaN,C
"Sandstrom, Miss. Marguerite Rut",11,1,3,female,4.0,1,1,PP 9549,16.7000,G6,S
"Bonnell, Miss. Elizabeth",12,1,1,female,58.0,0,0,113783,26.5500,C103,S
"Saundercock, Mr. William Henry",13,0,3,male,20.0,0,0,A/5. 2151,8.0500,NaN,S
"Andersson, Mr. Anders Johan",14,0,3,male,39.0,1,5,347082,31.2750,NaN,S
"Vestrom, Miss. Hulda Amanda Adolfina",15,0,3,female,14.0,0,0,350406,7.8542,NaN,S
"Hewlett, Mrs. (Mary D Kingcome)",16,1,2,female,55.0,0,0,248706,16.0000,NaN,S
"Rice, Master. Eugene",17,0,3,male,2.0,4,1,382652,29.1250,NaN,Q
"Williams, Mr. Charles Eugene",18,1,2,male,NaN,0,0,244373,13.0000,NaN,S
"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",19,0,3,female,31.0,1,0,345763,18.0000,NaN,S
"Masselmani, Mrs. Fatima",20,1,3,female,NaN,0,0,2649,7.2250,NaN,C
"Fynney, Mr. Joseph J",21,0,2,male,35.0,0,0,239865,26.0000,NaN,S
"Beesley, Mr. Lawrence",22,1,2,male,34.0,0,0,248698,13.0000,D56,S
"McGowan, Miss. Anna ""Annie""",23,1,3,female,15.0,0,0,330923,8.0292,NaN,Q
"Sloper, Mr. William Thompson",24,1,1,male,28.0,0,0,113788,35.5000,A6,S

In [83]:
csv7=pd.read_csv('/content/Titanic.csv',header=2)
csv7

,2,1,1.1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38,1.2,0,PC 17599,71.2833,C85,C
0,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
5,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
6,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
7,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
8,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
9,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
10,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
11,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
12,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
13,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
14,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
15,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
16,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
17,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
18,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
19,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
20,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
21,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [87]:
csv8=pd.read_csv('/content/Titanic.csv',names=['col1','col2','col3','col4','col5','col6','col7','col8','col9','col10'])
csv8

,,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10
PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.925,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1,C123,S
5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.05,NaN,S
6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,E46,S
8,0,3,"Palsson, Master. Gosta Leonard",male,2,3,1,349909,21.075,NaN,S
9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27,0,2,347742,11.1333,NaN,S
10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14,1,0,237736,30.0708,NaN,C
11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4,1,1,PP 9549,16.7,G6,S
12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.55,C103,S
13,0,3,"Saundercock, Mr. William Henry",male,20,0,0,A/5. 2151,8.05,NaN,S
14,0,3,"Andersson, Mr. Anders Johan",male,39,1,5,347082,31.275,NaN,S
15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14,0,0,350406,7.8542,NaN,S
16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55,0,0,248706,16,NaN,S
17,0,3,"Rice, Master. Eugene",male,2,4,1,382652,29.125,NaN,Q
18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13,NaN,S
19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31,1,0,345763,18,NaN,S
20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.225,NaN,C
21,0,2,"Fynney, Mr. Joseph J",male,35,0,0,239865,26,NaN,S
22,1,2,"Beesley, Mr. Lawrence",male,34,0,0,248698,13,D56,S
23,1,3,"McGowan, Miss. Anna ""Annie""",female,15,0,0,330923,8.0292,NaN,Q
24,1,1,"Sloper, Mr. William Thompson",male,28,0,0,113788,35.5,A6,S

In [90]:
csv9=pd.read_csv('/content/Titanic.csv',dtype={'Pclass':'float'})
csv9

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3.0,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3.0,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3.0,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3.0,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1.0,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3.0,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3.0,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1.0,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3.0,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3.0,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3.0,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2.0,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3.0,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2.0,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3.0,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3.0,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2.0,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2.0,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3.0,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1.0,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

# Pandas **Function**

In [92]:
csv1=pd.read_csv('/content/Titanic.csv')
csv1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [93]:
csv1.index

RangeIndex(start=0, stop=24, step=1)

In [94]:
csv1.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [96]:
csv1.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,24.000000,24.000000,24.000000,21.000000,24.000000,24.000000,24.000000
mean,12.500000,0.541667,2.375000,28.000000,0.583333,0.416667,21.938192
std,7.071068,0.508977,0.824226,16.297239,1.017955,1.100066,17.031278
min,1.000000,0.000000,1.000000,2.000000,0.000000,0.000000,7.225000
25%,6.750000,0.000000,2.000000,15.000000,0.000000,0.000000,8.050000
50%,12.500000,1.000000,3.000000,28.000000,0.000000,0.000000,16.350000
75%,18.250000,1.000000,3.000000,35.000000,1.000000,0.000000,29.361450
max,24.000000,1.000000,3.000000,58.000000,4.000000,5.000000,71.283300

In [97]:
csv1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [99]:
csv1.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [100]:
csv1.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [102]:
csv1[7:10]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [103]:
print(type(csv1))

<class 'pandas.core.frame.DataFrame'>

In [104]:
csv1.index.array

<NumpyExtensionArray>
[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23]
Length: 24, dtype: int64

In [105]:
csv1.sort_index(axis=0,ascending=False)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S

In [106]:
csv1.loc[0,'Name']='python'
csv1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,python,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

In [107]:
csv1.loc[[2,3],['Name','Sex']]

                                           Name     Sex
2                        Heikkinen, Miss. Laina  female
3  Futrelle, Mrs. Jacques Heath (Lily May Peel)  female

In [112]:
csv1.loc[:,['Name','Sex']]

                                                 Name     Sex
0                                              python    male
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female
2                              Heikkinen, Miss. Laina  female
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female
4                            Allen, Mr. William Henry    male
5                                    Moran, Mr. James    male
6                             McCarthy, Mr. Timothy J    male
7                      Palsson, Master. Gosta Leonard    male
8   Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female
9                 Nasser, Mrs. Nicholas (Adele Achem)  female
10                    Sandstrom, Miss. Marguerite Rut  female
11                           Bonnell, Miss. Elizabeth  female
12                     Saundercock, Mr. William Henry    male
13                        Andersson, Mr. Anders Johan    male
14               Vestrom, Miss. Hulda Amanda Adolfina  female
15                   Hewlett, Mrs. (Mary D Kingcome)   female
16                               Rice, Master. Eugene    male
17                       Williams, Mr. Charles Eugene    male
18  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female
19                            Masselmani, Mrs. Fatima  female
20                               Fynney, Mr. Joseph J    male
21                              Beesley, Mr. Lawrence    male
22                        McGowan, Miss. Anna "Annie"  female
23                       Sloper, Mr. William Thompson    male

In [114]:
csv1.loc[[2,3],:]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.100,C123,S

In [115]:
csv1.drop('Fare',axis=1)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Cabin,Embarked
0,1,0,3,python,male,22.0,1,0,A/5 21171,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,A6,S

In [116]:
csv1.drop(1,axis=0)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,python,male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S

# dropna & **fillna**

In [124]:
csv=pd.read_csv('/content/sample.csv')
csv

     A     B     C   D  E
0  1.0  10.0  21.0  11  2
1  2.0   9.0  22.0  12  9
2  3.0   8.0  23.0  13  3
3  4.0   NaN   NaN  14  7
4  5.0   6.0  25.0  15  3
5  NaN   5.0  26.0  17  9
6  7.0   4.0  27.0  18  2
7  8.0   3.0   NaN  16  7
8  9.0   NaN  29.0  19  4
9  NaN   1.0  30.0  20  7

In [125]:
csv.dropna()

     A     B     C   D  E
0  1.0  10.0  21.0  11  2
1  2.0   9.0  22.0  12  9
2  3.0   8.0  23.0  13  3
4  5.0   6.0  25.0  15  3
6  7.0   4.0  27.0  18  2

In [127]:
csv.dropna(axis=1)

    D  E
0  11  2
1  12  9
2  13  3
3  14  7
4  15  3
5  17  9
6  18  2
7  16  7
8  19  4
9  20  7

In [129]:
csv.dropna(subset=['C'])

     A     B     C   D  E
0  1.0  10.0  21.0  11  2
1  2.0   9.0  22.0  12  9
2  3.0   8.0  23.0  13  3
4  5.0   6.0  25.0  15  3
5  NaN   5.0  26.0  17  9
6  7.0   4.0  27.0  18  2
8  9.0   NaN  29.0  19  4
9  NaN   1.0  30.0  20  7